# This is a basic workflow to help you get started with Actions

name: Seqfu-Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: NIM Lang Alpine
       # You may pin to the exact commit or the version.
       # uses: skynet-core/nim@5c3d72356c8763b02fb045a14d7d83a563cd2b12
        uses: skynet-core/nim@v1.2
        with:
          # Command to run
          command: cd nim && sudo apk add zlib-dev && nim --version && nimble --version && nimble build --nimcache:/tmp/.cache --nimbleDir:/tmp/.nimble --gcc.exe:gcc --gcc.linkerexe:gcc --passL:-lz -d:useLibzipSrc -d:release --opt:speed -y && ./bin/fu-digest -h && bash test/test.sh


 